-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 21:26:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proprietario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identity_card_id` INT NOT NULL,
  PRIMARY KEY (`id`, `identity_card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carta_conducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carta_conducao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_expiracao` DATE NOT NULL,
  `categoria_veiculo` INT NOT NULL,
  `restricoes` TEXT NULL,
  `numero_identificao_veiculo` INT NOT NULL,
  `assinatura_emissor_doc` VARCHAR(50) NOT NULL,
  `proprietario_id` INT NOT NULL,
  `proprietario_identity_card_id` INT NOT NULL,
  `expirada` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `proprietario_id`, `proprietario_identity_card_id`),
  INDEX `fk_carta_conducao_proprietario_idx` (`proprietario_id` ASC, `proprietario_identity_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_carta_conducao_proprietario`
    FOREIGN KEY (`proprietario_id` , `proprietario_identity_card_id`)
    REFERENCES `mydb`.`proprietario` (`id` , `identity_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilhete_identidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bilhete_identidade` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `filiacao` TEXT NULL,
  `numero_bilhete` TEXT NOT NULL,
  `residencia` TEXT NOT NULL,
  `natural_de` TEXT NOT NULL,
  `provincia` TEXT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `estado_civil` VARCHAR(25) NOT NULL,
  `emitido_em` DATE NOT NULL,
  `valido_ate` DATE NOT NULL,
  `proprietario_id` INT NOT NULL,
  `proprietario_identity_card_id` INT NOT NULL,
  `altura` FLOAT NOT NULL,
  `expirada` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `proprietario_id`, `proprietario_identity_card_id`),
  INDEX `fk_bilhete_identidade_proprietario1_idx` (`proprietario_id` ASC, `proprietario_identity_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_bilhete_identidade_proprietario1`
    FOREIGN KEY (`proprietario_id` , `proprietario_identity_card_id`)
    REFERENCES `mydb`.`proprietario` (`id` , `identity_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titulo_veiculo_automovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titulo_veiculo_automovel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(100) NOT NULL,
  `chassis` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `ano_fabricacao` DATE NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_registro` DATE NOT NULL,
  `numero_registro` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `tipo_combustivel` VARCHAR(45) NOT NULL,
  `numero_lugares` INT NOT NULL,
  `potencia_motor` TEXT NOT NULL,
  `nome_proprietario` TEXT NULL,
  `morada_proprietario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agente_transito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agente_transito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `cellphone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livrete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livrete` (
  `id` INT NOT NULL,
  `matricula` VARCHAR(100) NOT NULL,
  `chassis` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(100) NULL,
  `categoria_veiculo` VARCHAR(20) NOT NULL,
  `numero_lugares` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `tipo_combustivel` VARCHAR(45) NOT NULL,
  `potencia_fiscal` TEXT NOT NULL,
  `data_emissao_matricula` DATE NOT NULL,
  `data_aquisicao_veiculo` DATE NOT NULL,
  `data_ultima_inspecao_tecnica` DATE NOT NULL,
  `classe_ambiental_veiculo` TEXT NOT NULL,
  `emissoes_dioxido_carbono_co2` INT NOT NULL,
  `peso_bruto` FLOAT NOT NULL,
  `obs` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` TEXT NULL,
  `proprietario_id` INT NOT NULL,
  `proprietario_identity_card_id` INT NOT NULL,
  `titulo_veiculo_automovel_id` INT NOT NULL,
  `livrete_id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `proprietario_id`, `proprietario_identity_card_id`, `titulo_veiculo_automovel_id`, `livrete_id`),
  INDEX `fk_veiculo_proprietario1_idx` (`proprietario_id` ASC, `proprietario_identity_card_id` ASC) VISIBLE,
  INDEX `fk_veiculo_titulo_veiculo_automovel1_idx` (`titulo_veiculo_automovel_id` ASC) VISIBLE,
  INDEX `fk_veiculo_livrete1_idx` (`livrete_id` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_proprietario1`
    FOREIGN KEY (`proprietario_id` , `proprietario_identity_card_id`)
    REFERENCES `mydb`.`proprietario` (`id` , `identity_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_titulo_veiculo_automovel1`
    FOREIGN KEY (`titulo_veiculo_automovel_id`)
    REFERENCES `mydb`.`titulo_veiculo_automovel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_livrete1`
    FOREIGN KEY (`livrete_id`)
    REFERENCES `mydb`.`livrete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguro` (
  `id` INT NULL AUTO_INCREMENT,
  `data_expiracao` DATE NOT NULL,
  `expirada` TINYINT NULL DEFAULT 0,
  `veiculo_id` INT NOT NULL,
  `veiculo_proprietario_id` INT NOT NULL,
  `veiculo_proprietario_identity_card_id` INT NOT NULL,
  `veiculo_titulo_veiculo_automovel_id` INT NOT NULL,
  `veiculo_livrete_id` INT NOT NULL,
  PRIMARY KEY (`id`, `veiculo_id`, `veiculo_proprietario_id`, `veiculo_proprietario_identity_card_id`, `veiculo_titulo_veiculo_automovel_id`, `veiculo_livrete_id`),
  INDEX `fk_seguro_veiculo1_idx` (`veiculo_id` ASC, `veiculo_proprietario_id` ASC, `veiculo_proprietario_identity_card_id` ASC, `veiculo_titulo_veiculo_automovel_id` ASC, `veiculo_livrete_id` ASC) VISIBLE,
  CONSTRAINT `fk_seguro_veiculo1`
    FOREIGN KEY (`veiculo_id` , `veiculo_proprietario_id` , `veiculo_proprietario_identity_card_id` , `veiculo_titulo_veiculo_automovel_id` , `veiculo_livrete_id`)
    REFERENCES `mydb`.`veiculo` (`id` , `proprietario_id` , `proprietario_identity_card_id` , `titulo_veiculo_automovel_id` , `livrete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inspecao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inspecao` (
  `id` INT NULL AUTO_INCREMENT,
  `data_expiracao` DATE NOT NULL,
  `expirada` TINYINT NULL DEFAULT 0,
  `veiculo_id` INT NOT NULL,
  `veiculo_proprietario_id` INT NOT NULL,
  `veiculo_proprietario_identity_card_id` INT NOT NULL,
  `veiculo_titulo_veiculo_automovel_id` INT NOT NULL,
  `veiculo_livrete_id` INT NOT NULL,
  PRIMARY KEY (`id`, `veiculo_id`, `veiculo_proprietario_id`, `veiculo_proprietario_identity_card_id`, `veiculo_titulo_veiculo_automovel_id`, `veiculo_livrete_id`),
  INDEX `fk_inspecao_veiculo1_idx` (`veiculo_id` ASC, `veiculo_proprietario_id` ASC, `veiculo_proprietario_identity_card_id` ASC, `veiculo_titulo_veiculo_automovel_id` ASC, `veiculo_livrete_id` ASC) VISIBLE,
  CONSTRAINT `fk_inspecao_veiculo1`
    FOREIGN KEY (`veiculo_id` , `veiculo_proprietario_id` , `veiculo_proprietario_identity_card_id` , `veiculo_titulo_veiculo_automovel_id` , `veiculo_livrete_id`)
    REFERENCES `mydb`.`veiculo` (`id` , `proprietario_id` , `proprietario_identity_card_id` , `titulo_veiculo_automovel_id` , `livrete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`licensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`licensa` (
  `id` INT NULL AUTO_INCREMENT,
  `data_expiracao` DATE NOT NULL,
  `expirada` TINYINT NULL DEFAULT 0,
  `veiculo_id` INT NOT NULL,
  `veiculo_proprietario_id` INT NOT NULL,
  `veiculo_proprietario_identity_card_id` INT NOT NULL,
  `veiculo_titulo_veiculo_automovel_id` INT NOT NULL,
  `veiculo_livrete_id` INT NOT NULL,
  PRIMARY KEY (`id`, `veiculo_id`, `veiculo_proprietario_id`, `veiculo_proprietario_identity_card_id`, `veiculo_titulo_veiculo_automovel_id`, `veiculo_livrete_id`),
  INDEX `fk_licensa_veiculo1_idx` (`veiculo_id` ASC, `veiculo_proprietario_id` ASC, `veiculo_proprietario_identity_card_id` ASC, `veiculo_titulo_veiculo_automovel_id` ASC, `veiculo_livrete_id` ASC) VISIBLE,
  CONSTRAINT `fk_licensa_veiculo1`
    FOREIGN KEY (`veiculo_id` , `veiculo_proprietario_id` , `veiculo_proprietario_identity_card_id` , `veiculo_titulo_veiculo_automovel_id` , `veiculo_livrete_id`)
    REFERENCES `mydb`.`veiculo` (`id` , `proprietario_id` , `proprietario_identity_card_id` , `titulo_veiculo_automovel_id` , `livrete_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

create database `board_manager`;
drop database board_manager;
drop tables `board_manager`.`license`, `board_manager`.`secure`, `board_manager`.`inspection`;
ALTER TABLE `infractions` DROP COLUMN `info_payment`;
ALTER TABLE `infractions` ADD COLUMN `info_payment` TEXT DEFAULT("Padrão");
ALTER TABLE `infractions` ADD COLUMN `paid` BOOL DEFAULT(False);